wowlinks:
  "amzn": "https://amazon.com"
  "msft": "https://onedrive.live.com"
  "gh": "https://github.com"
  "g": "https://google.com"
  "yt": "https://www.youtube.com"
  "mdum": "https://medium.com"
